import type { PatternCard, SystemDesignTopic, WeekPlan } from "@/lib/types";

export const roadmapWeeks = [
  {phase:'M1',week:1,title:'Arrays & Strings',color:'#1D9E75',bg:'#E1F5EE',days:['Mon: Two Pointers intro + 2 Easy','Tue: Sliding Window intro + 2 Easy','Wed: Prefix Sum + 2 Easy/Med','Thu: String manipulation + 2 Med','Fri: Review + revisit Day 1 problems','Sat: Timed mock (3 problems)','Sun: SD — Latency, Throughput, Availability'],topics:['Two Pointers (Two Sum, 3Sum, Container With Most Water)','Sliding Window (Max Subarray, Longest Substring Without Repeat)','Prefix Sum (Subarray Sum Equals K)','String patterns (Valid Anagram, Group Anagrams)']},
  {phase:'M1',week:2,title:'Hashing & Binary Search',color:'#1D9E75',bg:'#E1F5EE',days:['Mon: HashMap patterns + 2 Easy','Tue: HashSet patterns + 2 Med','Wed: Binary Search on sorted array','Thu: Binary Search on answer','Fri: Review + re-solve W1 hard ones','Sat: Timed mock','Sun: SD — CAP Theorem, SQL vs NoSQL'],topics:['HashMap: Two Sum, Top K Frequent, LRU Cache','Binary Search: Search in Rotated Array, Find Minimum','Binary Search on Answer: Koko Eating Bananas, Capacity to Ship']},
  {phase:'M1',week:3,title:'Linked Lists & Stacks',color:'#1D9E75',bg:'#E1F5EE',days:['Mon: LL basics + Reverse LL','Tue: LL two pointers (fast/slow)','Wed: Stack fundamentals','Thu: Monotonic Stack patterns','Fri: Review week','Sat: Timed mock','Sun: SD — Load Balancing, Caching basics'],topics:['LL: Reverse, Merge Two Sorted, LRU Cache','Fast/Slow pointers: Detect Cycle, Middle of LL','Stack: Valid Parentheses, Min Stack, Daily Temperatures','Monotonic Stack: Next Greater Element, Largest Rectangle in Histogram']},
  {phase:'M1',week:4,title:'Trees — BFS & DFS',color:'#1D9E75',bg:'#E1F5EE',days:['Mon: Tree DFS (preorder, inorder, postorder)','Tue: Tree problems with DFS','Wed: BFS level order','Thu: BFS problems','Fri: Review + spaced revision W1–W2','Sat: Timed mock','Sun: SD — DNS, CDN, Proxies'],topics:['DFS: Max Depth, Path Sum, Lowest Common Ancestor','BFS: Level Order, Right Side View, Zigzag Traversal','BST: Validate BST, Kth Smallest','Trie: Implement Trie, Word Search II']},
  {phase:'M2',week:5,title:'Heaps & Priority Queues',color:'#7F77DD',bg:'#EEEDFE',days:['Mon: Heap intro + Top K patterns','Tue: K-way merge pattern','Wed: Median from data stream','Thu: Meeting rooms / interval heap','Fri: Review','Sat: Timed mock (start doing 1 Hard)','Sun: SD — Consistent Hashing, Sharding'],topics:['Top K Frequent Elements, K Closest Points','Merge K Sorted Lists','Find Median From Data Stream','Task Scheduler, Reorganize String']},
  {phase:'M2',week:6,title:'Graphs I — DFS/BFS',color:'#7F77DD',bg:'#EEEDFE',days:['Mon: Graph representation, DFS','Tue: BFS on graph, shortest path','Wed: Union Find (DSU)','Thu: Topological Sort (Kahn\'s)','Fri: Review','Sat: Timed mock','Sun: SD — Design URL Shortener'],topics:['Number of Islands, Clone Graph, Pacific Atlantic','Course Schedule (topological sort)','Union Find: Redundant Connection, Accounts Merge','Word Ladder (BFS shortest path)']},
  {phase:'M2',week:7,title:'Graphs II + Backtracking',color:'#7F77DD',bg:'#EEEDFE',days:['Mon: Dijkstra\'s Bellman-Ford','Tue: Backtracking framework','Wed: Subsets, Permutations, Combinations','Thu: Sudoku, N-Queens, Word Search','Fri: Review + spaced revision W3–W4','Sat: Timed mock','Sun: SD — Design Key-Value Store / Redis'],topics:['Dijkstra: Network Delay Time, Cheapest Flights','Backtracking: Subsets, Permutations, Combination Sum','Word Search, Palindrome Partitioning','N-Queens (pruning practice)']},
  {phase:'M2',week:8,title:'Dynamic Programming I',color:'#7F77DD',bg:'#EEEDFE',days:['Mon: 1D DP (Fibonacci pattern)','Tue: 0/1 Knapsack','Wed: Unbounded Knapsack','Thu: LCS, LIS patterns','Fri: Review','Sat: Timed mock','Sun: SD — Design Twitter / News Feed'],topics:['Climbing Stairs, House Robber, Coin Change','Partition Equal Subset Sum','Longest Common Subsequence, Longest Increasing Subsequence','Word Break, Decode Ways']},
  {phase:'M2',week:9,title:'DP II + Intervals',color:'#7F77DD',bg:'#EEEDFE',days:['Mon: 2D DP (grids)','Tue: DP on strings','Wed: Intervals merge/insert','Thu: Greedy + Intervals','Fri: Review + spaced revision W5–W6','Sat: Timed mock','Sun: SD — Design Rate Limiter'],topics:['Unique Paths, Minimum Path Sum, Edit Distance','Palindromic Substrings, Longest Palindromic Substring','Merge Intervals, Meeting Rooms II','Jump Game (greedy)']},
  {phase:'M3',week:10,title:'Hard Problems + Bit Manipulation',color:'#D85A30',bg:'#FAECE7',days:['Mon: Bit manipulation patterns','Tue: Hard DP revisit','Wed: Hard Graphs revisit','Thu: Hard Mixed problems','Fri: Full spaced revision W1–W9','Sat: Mock interview simulation (60 min)','Sun: SD — Design Distributed Cache'],topics:['Single Number, Missing Number, Reverse Bits','Hard DP: Burst Balloons, Regular Expression Match','Hard Graph: Alien Dictionary, Critical Connections','Bit: Power of Two, Counting Bits']},
  {phase:'M3',week:11,title:'Mock Interviews + Weak Areas',color:'#D85A30',bg:'#FAECE7',days:['Mon: Identify 3 weakest pattern areas','Tue: Deep drill on weak area 1','Wed: Deep drill on weak area 2','Thu: Deep drill on weak area 3','Fri: Timed random 3-problem set','Sat: Full mock interview (coding + SD)','Sun: SD — Design Notification System + Kafka'],topics:['Mock on pramp.com / interviewing.io','Revisit all flagged Hards','SD: Deep dive on message queues, pub-sub','Behavioral: STAR format for 5 key stories']},
  {phase:'M3',week:12,title:'Final Polish + Interview Week',color:'#D85A30',bg:'#FAECE7',days:['Mon: Light review — patterns cheat sheet','Tue: 3 problems (familiar patterns only)','Wed: 1 SD mock, review notes','Thu: Light review, rest','Fri: Final review — no new problems','Sat: Rest / light review','Sun: REST — you\'re ready!'],topics:['Review your personal notes, not new problems','SD: Review all 12 case study designs','Behavioral: Practice out loud 5 stories','Sleep well, eat well, trust the process']},
] satisfies WeekPlan[];

export const roadmapPatterns = [
  {name:'Two Pointers',tag:'Arrays',bg:'#E1F5EE',tc:'#0F6E56',desc:'Use two indices moving toward each other or at different speeds.',ex:'Two Sum II, 3Sum, Container With Most Water, Trapping Rain Water'},
  {name:'Sliding Window',tag:'Arrays/Strings',bg:'#E1F5EE',tc:'#0F6E56',desc:'Maintain a window over a sequence, expand/shrink based on condition.',ex:'Longest Substring Without Repeating, Minimum Window Substring'},
  {name:'Fast & Slow Pointers',tag:'Linked List',bg:'#E1F5EE',tc:'#0F6E56',desc:'Two pointers at different speeds to find cycles or midpoints.',ex:'Linked List Cycle, Find Middle, Happy Number'},
  {name:'Binary Search',tag:'Sorted/Answer',bg:'#EEEDFE',tc:'#534AB7',desc:'Eliminate half the search space each step. Works on sorted arrays or monotonic answer spaces.',ex:'Search in Rotated Array, Koko Eating Bananas, Median of Two Sorted Arrays'},
  {name:'BFS / Level Order',tag:'Graphs/Trees',bg:'#EEEDFE',tc:'#534AB7',desc:'Explore nodes level by level using a queue. Best for shortest paths in unweighted graphs.',ex:'Word Ladder, Binary Tree Right Side View, Rotten Oranges'},
  {name:'DFS / Backtracking',tag:'Trees/Graphs',bg:'#EEEDFE',tc:'#534AB7',desc:'Explore all paths recursively. Add pruning to cut invalid branches early.',ex:'Subsets, Permutations, N-Queens, Word Search, Sudoku'},
  {name:'Dynamic Programming',tag:'Optimization',bg:'#FAECE7',tc:'#993C1D',desc:'Break into subproblems, memoize or tabulate. Identify: choice → recurrence → base case.',ex:'Coin Change, LCS, Edit Distance, Burst Balloons'},
  {name:'Merge Intervals',tag:'Intervals',bg:'#FAECE7',tc:'#993C1D',desc:'Sort by start, merge overlapping intervals. Key: check if cur.start ≤ prev.end.',ex:'Merge Intervals, Insert Interval, Meeting Rooms II'},
  {name:'Top K / Heap',tag:'Priority Queue',bg:'#FAEEDA',tc:'#854F0B',desc:'Use a min-heap of size K to track top K elements efficiently in O(n log k).',ex:'Top K Frequent, K Closest Points, Merge K Sorted Lists'},
  {name:'Monotonic Stack',tag:'Stack',bg:'#FAEEDA',tc:'#854F0B',desc:'Maintain increasing or decreasing stack to find next greater/smaller element in O(n).',ex:'Daily Temperatures, Largest Rectangle in Histogram'},
  {name:'Union Find (DSU)',tag:'Graphs',bg:'#E6F1FB',tc:'#185FA5',desc:'Efficiently merge sets and check connectivity. Use path compression + union by rank.',ex:'Number of Connected Components, Redundant Connection, Accounts Merge'},
  {name:'Topological Sort',tag:'Graphs/DAG',bg:'#E6F1FB',tc:'#185FA5',desc:'Order nodes with dependencies using BFS (Kahn\'s) or DFS. Only on DAGs.',ex:'Course Schedule, Alien Dictionary, Build Order'},
  {name:'Prefix Sum',tag:'Arrays',bg:'#EAF3DE',tc:'#3B6D11',desc:'Precompute cumulative sums to answer range queries in O(1).',ex:'Subarray Sum Equals K, Range Sum Query, Product Except Self'},
  {name:'Trie (Prefix Tree)',tag:'Strings',bg:'#EAF3DE',tc:'#3B6D11',desc:'Tree for storing strings character by character. O(L) search/insert.',ex:'Implement Trie, Word Search II, Auto-complete, Replace Words'},
  {name:'Greedy',tag:'Optimization',bg:'#FCEBEB',tc:'#A32D2D',desc:'Always pick the locally optimal choice. Prove greedy works via exchange argument.',ex:'Jump Game, Gas Station, Assign Cookies, Task Scheduler'},
] satisfies PatternCard[];

export const systemDesignTopics = [
  {week:'Week 5 (M2)',title:'Foundations',items:['Scalability: vertical vs horizontal','CAP theorem + PACELC','Latency, throughput, availability','Load balancers (L4 vs L7)']},
  {week:'Week 6 (M2)',title:'Data & Storage',items:['SQL vs NoSQL trade-offs','Sharding strategies','Replication (leader-follower)','Consistent hashing']},
  {week:'Week 7 (M2)',title:'Caching & CDN',items:['Cache eviction (LRU, LFU)','Write-through vs write-back','CDN & edge caching','Redis patterns']},
  {week:'Week 8 (M2)',title:'Case Study: URL Shortener + Twitter',items:['Base62 encoding, ID generation','Fan-out on write vs read','Timeline generation','Snowflake ID, UUID']},
  {week:'Week 9 (M2)',title:'Messaging & Async',items:['Message queues (Kafka, RabbitMQ)','Pub-Sub pattern','Event-driven architecture','Rate limiting (token bucket)']},
  {week:'Week 10 (M3)',title:'Distributed Systems',items:['Design key-value store (DynamoDB)','Consensus: Raft / Paxos overview','Distributed cache (Memcached)','2-phase commit']},
  {week:'Week 11 (M3)',title:'Real-time & Search',items:['Design notification system','WebSockets vs long-polling','Search: Elasticsearch basics','Design type-ahead / autocomplete']},
  {week:'Week 12 (M3)',title:'Mega Round Review',items:['Design YouTube / Netflix','Design Uber / Lyft','Design WhatsApp / Slack','Review all designs + trade-offs']},
] satisfies SystemDesignTopic[];
