import type { PatternCard, SystemDesignTopic, WeekPlan } from "@/lib/types";

export const roadmapWeeks = [
  {phase:'M1',week:1,title:'Arrays & Strings',color:'#1D9E75',bg:'#E1F5EE',intro:'You already use arrays and strings daily at work — this week is about learning the interview-specific patterns built on top of them. Two Pointers, Sliding Window, and Prefix Sum are the three techniques that turn brute-force O(n²) array problems into clean O(n) solutions. Master these first because they appear in roughly 30% of all interview problems.',days:['Mon: Two Pointers intro + 2 Easy','Tue: Sliding Window intro + 2 Easy','Wed: Prefix Sum + 2 Easy/Med','Thu: String manipulation + 2 Med','Fri: Review + revisit Day 1 problems','Sat: Timed mock (3 problems)','Sun: SD — Latency, Throughput, Availability'],topics:['Two Pointers (Two Sum, 3Sum, Container With Most Water)','Sliding Window (Max Subarray, Longest Substring Without Repeat)','Prefix Sum (Subarray Sum Equals K)','String patterns (Valid Anagram, Group Anagrams)']},
  {phase:'M1',week:2,title:'Hashing & Binary Search',color:'#1D9E75',bg:'#E1F5EE',intro:'Hashing and Binary Search are the two tools that solve lookup and search problems efficiently. HashMap and HashSet let you build O(1) lookups from raw data, while Binary Search eliminates half your search space each step. Together they handle "find the answer" questions in interviews — you\'ll see them in 25-30% of medium problems.',days:['Mon: HashMap patterns + 2 Easy','Tue: HashSet patterns + 2 Med','Wed: Binary Search on sorted array','Thu: Binary Search on answer','Fri: Review + re-solve W1 hard ones','Sat: Timed mock','Sun: SD — CAP Theorem, SQL vs NoSQL'],topics:['HashMap: Two Sum, Top K Frequent, LRU Cache','Binary Search: Search in Rotated Array, Find Minimum','Binary Search on Answer: Koko Eating Bananas, Capacity to Ship']},
  {phase:'M1',week:3,title:'Linked Lists & Stacks',color:'#1D9E75',bg:'#E1F5EE',intro:'Linked Lists and Stacks are the foundational data structures for in-place modifications and LIFO operations. The fast-and-slow pointer technique with Linked Lists is a classic interview trick for cycle detection and finding midpoints. Monotonic Stacks solve a whole category of "next greater element" problems that look impossible until you know the pattern.',days:['Mon: LL basics + Reverse LL','Tue: LL two pointers (fast/slow)','Wed: Stack fundamentals','Thu: Monotonic Stack patterns','Fri: Review week','Sat: Timed mock','Sun: SD — Load Balancing, Caching basics'],topics:['LL: Reverse, Merge Two Sorted, LRU Cache','Fast/Slow pointers: Detect Cycle, Middle of LL','Stack: Valid Parentheses, Min Stack, Daily Temperatures','Monotonic Stack: Next Greater Element, Largest Rectangle in Histogram']},
  {phase:'M1',week:4,title:'Trees — BFS & DFS',color:'#1D9E75',bg:'#E1F5EE',intro:'Trees are everywhere in interviews — binary search trees for lookups, tries for string problems, N-ary trees for hierarchies. DFS and BFS are the two ways to traverse them, and this week locks in your instincts for when to use each. Tree recursion is different from array recursion; master it now because you\'ll build on it in Weeks 5-7.',days:['Mon: Tree DFS (preorder, inorder, postorder)','Tue: Tree problems with DFS','Wed: BFS level order','Thu: BFS problems','Fri: Review + spaced revision W1–W2','Sat: Timed mock','Sun: SD — DNS, CDN, Proxies'],topics:['DFS: Max Depth, Path Sum, Lowest Common Ancestor','BFS: Level Order, Right Side View, Zigzag Traversal','BST: Validate BST, Kth Smallest','Trie: Implement Trie, Word Search II']},
  {phase:'M2',week:5,title:'Heaps & Priority Queues',color:'#7F77DD',bg:'#EEEDFE',intro:'Heaps let you maintain a partial order over a dataset without fully sorting it — critical for "top K" problems and median tracking. You\'re moving from single-path patterns (arrays, strings) to graph-like structures this month. Priority Queue is your first new mental model; it unlocks solutions to streaming data problems that would be O(n log n) with sorting.',days:['Mon: Heap intro + Top K patterns','Tue: K-way merge pattern','Wed: Median from data stream','Thu: Meeting rooms / interval heap','Fri: Review','Sat: Timed mock (start doing 1 Hard)','Sun: SD — Consistent Hashing, Sharding'],topics:['Top K Frequent Elements, K Closest Points','Merge K Sorted Lists','Find Median From Data Stream','Task Scheduler, Reorganize String']},
  {phase:'M2',week:6,title:'Graphs I — DFS/BFS',color:'#7F77DD',bg:'#EEEDFE',intro:'Graphs are the abstraction for connected-component problems and reachability. This week you\'ll learn to represent graphs, traverse them, and detect cycles using Union Find (DSU). Topological Sort solves dependency-order problems — it\'s a classic medium-hard that separates people who understand DAGs from those who just memorize solutions.',days:['Mon: Graph representation, DFS','Tue: BFS on graph, shortest path','Wed: Union Find (DSU)','Thu: Topological Sort (Kahn\'s)','Fri: Review','Sat: Timed mock','Sun: SD — Design URL Shortener'],topics:['Number of Islands, Clone Graph, Pacific Atlantic','Course Schedule (topological sort)','Union Find: Redundant Connection, Accounts Merge','Word Ladder (BFS shortest path)']},
  {phase:'M2',week:7,title:'Graphs II + Backtracking',color:'#7F77DD',bg:'#EEEDFE',intro:'Dijkstra solves weighted shortest-path problems — learn it well because interviews love disguising graph problems as "cheapest route" or "minimum cost" questions. Backtracking is the systematic way to explore all possibilities without brute force. It powers Sudoku, N-Queens, and permutation problems. The key insight: prune early, don\'t generate all branches.',days:['Mon: Dijkstra\'s Bellman-Ford','Tue: Backtracking framework','Wed: Subsets, Permutations, Combinations','Thu: Sudoku, N-Queens, Word Search','Fri: Review + spaced revision W3–W4','Sat: Timed mock','Sun: SD — Design Key-Value Store / Redis'],topics:['Dijkstra: Network Delay Time, Cheapest Flights','Backtracking: Subsets, Permutations, Combination Sum','Word Search, Palindrome Partitioning','N-Queens (pruning practice)']},
  {phase:'M2',week:8,title:'Dynamic Programming I',color:'#7F77DD',bg:'#EEEDFE',intro:'Dynamic Programming is where interviews separate confident engineers from the rest. It\'s not magic — it\'s optimization via memoization and state choice. Start with 1D DP (Fibonacci-like) and 0/1 Knapsack. The mental model: "What subproblem can I solve to build toward the full answer?" Once this clicks, you\'ll solve problems that looked impossible.',days:['Mon: 1D DP (Fibonacci pattern)','Tue: 0/1 Knapsack','Wed: Unbounded Knapsack','Thu: LCS, LIS patterns','Fri: Review','Sat: Timed mock','Sun: SD — Design Twitter / News Feed'],topics:['Climbing Stairs, House Robber, Coin Change','Partition Equal Subset Sum','Longest Common Subsequence, Longest Increasing Subsequence','Word Break, Decode Ways']},
  {phase:'M2',week:9,title:'DP II + Intervals',color:'#7F77DD',bg:'#EEEDFE',intro:'2D DP and interval problems are where you apply DP to grids and ranges. Edit Distance and Longest Palindromic Substring are classics that show up on hard rounds. Interval merging and greedy interval problems are a separate sub-category. By the end of Month 2, you\'ll have seen nearly every pattern structure in lower-medium to medium problems.',days:['Mon: 2D DP (grids)','Tue: DP on strings','Wed: Intervals merge/insert','Thu: Greedy + Intervals','Fri: Review + spaced revision W5–W6','Sat: Timed mock','Sun: SD — Design Rate Limiter'],topics:['Unique Paths, Minimum Path Sum, Edit Distance','Palindromic Substrings, Longest Palindromic Substring','Merge Intervals, Meeting Rooms II','Jump Game (greedy)']},
  {phase:'M3',week:10,title:'Hard Problems + Bit Manipulation',color:'#D85A30',bg:'#FAECE7',intro:'Hard problems are where your foundations snap together. You\'re not learning new patterns; you\'re combining old ones under pressure. Bit Manipulation is a small toolkit for problems involving binary representations and XOR tricks. This week is high-volume mock interview practice — speed and accuracy matter now.',days:['Mon: Bit manipulation patterns','Tue: Hard DP revisit','Wed: Hard Graphs revisit','Thu: Hard Mixed problems','Fri: Full spaced revision W1–W9','Sat: Mock interview simulation (60 min)','Sun: SD — Design Distributed Cache'],topics:['Single Number, Missing Number, Reverse Bits','Hard DP: Burst Balloons, Regular Expression Match','Hard Graph: Alien Dictionary, Critical Connections','Bit: Power of Two, Counting Bits']},
  {phase:'M3',week:11,title:'Mock Interviews + Weak Areas',color:'#D85A30',bg:'#FAECE7',intro:'You\'ve covered all patterns. This week is about identifying the 2-3 areas where you still lose time or confidence, and drilling them until they\'re automatic. Full mock interviews on platforms like pramp.io force you to verbalize your thinking and handle interviewer questions in real time. This is where interview stamina and communication get tested.',days:['Mon: Identify 3 weakest pattern areas','Tue: Deep drill on weak area 1','Wed: Deep drill on weak area 2','Thu: Deep drill on weak area 3','Fri: Timed random 3-problem set','Sat: Full mock interview (coding + SD)','Sun: SD — Design Notification System + Kafka'],topics:['Mock on pramp.com / interviewing.io','Revisit all flagged Hards','SD: Deep dive on message queues, pub-sub','Behavioral: STAR format for 5 key stories']},
  {phase:'M3',week:12,title:'Final Polish + Interview Week',color:'#D85A30',bg:'#FAECE7',intro:'This final week is about confidence and consistency, not new material. Light review of your weak areas, 5-10 minute ramp-up problems to warm your brain, and most importantly: rest. You\'ve built a 12-week foundation. Real interviews start now — trust your preparation and communicate clearly with your interviewer.',days:['Mon: Light review — patterns cheat sheet','Tue: 3 problems (familiar patterns only)','Wed: 1 SD mock, review notes','Thu: Light review, rest','Fri: Final review — no new problems','Sat: Rest / light review','Sun: REST — you\'re ready!'],topics:['Review your personal notes, not new problems','SD: Review all 12 case study designs','Behavioral: Practice out loud 5 stories','Sleep well, eat well, trust the process']},
] satisfies WeekPlan[];

export const roadmapPatterns = [
  {name:'Two Pointers',tag:'Arrays',bg:'#E1F5EE',tc:'#0F6E56',desc:'Use two indices moving toward each other or at different speeds.',signal:'Problem mentions sorted array, or asks to find pairs/triplets satisfying a condition, or says "in-place" with O(1) space.',edgeCases:'Empty array, single element, all-same values, array with negatives when looking for target sums.',ex:'Two Sum II, 3Sum, Container With Most Water, Trapping Rain Water'},
  {name:'Sliding Window',tag:'Arrays/Strings',bg:'#E1F5EE',tc:'#0F6E56',desc:'Maintain a window over a sequence, expand/shrink based on condition.',signal:'Asks for longest/shortest subarray or substring satisfying a constraint; constraint is checkable incrementally (adding/removing one element).',edgeCases:'Empty string, window larger than input, all elements satisfy or none satisfy, duplicate characters or values.',ex:'Longest Substring Without Repeating, Minimum Window Substring'},
  {name:'Fast & Slow Pointers',tag:'Linked List',bg:'#E1F5EE',tc:'#0F6E56',desc:'Two pointers at different speeds to find cycles or midpoints.',signal:'Linked List problem, or need to find cycle/midpoint without storing all nodes, or "detect loop" language.',edgeCases:'Single node, two-node list, cycle at start, cycle in middle, no cycle present, fast pointer skips slow pointer.',ex:'Linked List Cycle, Find Middle, Happy Number'},
  {name:'Binary Search',tag:'Sorted/Answer',bg:'#EEEDFE',tc:'#534AB7',desc:'Eliminate half the search space each step. Works on sorted arrays or monotonic answer spaces.',signal:'Array is sorted, or problem asks "find the minimum X where condition is true", or searching in rotated/shifted data.',edgeCases:'Single element, all elements same, element at boundaries, element not in array, duplicate values in rotated array.',ex:'Search in Rotated Array, Koko Eating Bananas, Median of Two Sorted Arrays'},
  {name:'BFS / Level Order',tag:'Graphs/Trees',bg:'#EEEDFE',tc:'#534AB7',desc:'Explore nodes level by level using a queue. Best for shortest paths in unweighted graphs.',signal:'Shortest path needed, level-by-level traversal, unweighted graph/tree, or "all nodes at distance K".',edgeCases:'Single node, disconnected graph, all same level, node visited multiple times (mark visited on offer, not poll).',ex:'Word Ladder, Binary Tree Right Side View, Rotten Oranges'},
  {name:'DFS / Backtracking',tag:'Trees/Graphs',bg:'#EEEDFE',tc:'#534AB7',desc:'Explore all paths recursively. Add pruning to cut invalid branches early.',signal:'"Find all combinations", "generate all", constraint satisfaction (Sudoku, N-Queens), or exhaustive search with pruning.',edgeCases:'Empty input, single element, all branches pruned, no valid solution, overlapping subsets, need path copying not reference.',ex:'Subsets, Permutations, N-Queens, Word Search, Sudoku'},
  {name:'Dynamic Programming',tag:'Optimization',bg:'#FAECE7',tc:'#993C1D',desc:'Break into subproblems, memoize or tabulate. Identify: choice → recurrence → base case.',signal:'"Minimum/maximum X", "count ways to", "can you reach", optimal substructure (solve one subproblem to solve larger).',edgeCases:'Base case boundary (k=0, i=0), negative/zero values, empty input, when memoization array is 1D vs 2D.',ex:'Coin Change, LCS, Edit Distance, Burst Balloons'},
  {name:'Merge Intervals',tag:'Intervals',bg:'#FAECE7',tc:'#993C1D',desc:'Sort by start, merge overlapping intervals. Key: check if cur.start ≤ prev.end.',signal:'Intervals, ranges, or "meeting rooms"; need to find overlaps or merge them; sort by start coordinate.',edgeCases:'No intervals, single interval, all overlap, none overlap, intervals touch at boundary (end = next start), insert into existing.',ex:'Merge Intervals, Insert Interval, Meeting Rooms II'},
  {name:'Top K / Heap',tag:'Priority Queue',bg:'#FAEEDA',tc:'#854F0B',desc:'Use a min-heap of size K to track top K elements efficiently in O(n log k).',signal:'"Top K", "K largest", "K smallest", "median", or "maintain top N efficiently from stream".',edgeCases:'K larger than input, K equals input size, K=1, negative numbers, duplicates in top K, min-heap for largest vs max-heap for smallest.',ex:'Top K Frequent, K Closest Points, Merge K Sorted Lists'},
  {name:'Monotonic Stack',tag:'Stack',bg:'#FAEEDA',tc:'#854F0B',desc:'Maintain increasing or decreasing stack to find next greater/smaller element in O(n).',signal:'"Next greater", "previous smaller", "histogram", "larger element to right/left"; store indices not values.',edgeCases:'No greater/smaller element exists, all same value, single element, empty input, need to handle elements after stack is processed.',ex:'Daily Temperatures, Largest Rectangle in Histogram'},
  {name:'Union Find (DSU)',tag:'Graphs',bg:'#E6F1FB',tc:'#185FA5',desc:'Efficiently merge sets and check connectivity. Use path compression + union by rank.',signal:'"Connected components", "same parent", "redundant edge", "find cycle" without DFS; disjoint set problems.',edgeCases:'Single element, all already connected, no connections, cycle detection, path compression optimization.',ex:'Number of Connected Components, Redundant Connection, Accounts Merge'},
  {name:'Topological Sort',tag:'Graphs/DAG',bg:'#E6F1FB',tc:'#185FA5',desc:'Order nodes with dependencies using BFS (Kahn\'s) or DFS. Only on DAGs.',signal:'"Dependency order", "prerequisites", "build order", "alien dictionary"; only works on directed acyclic graphs (DAGs).',edgeCases:'Cycle present (no valid ordering), single node, disconnected components, all nodes depend on each node.',ex:'Course Schedule, Alien Dictionary, Build Order'},
  {name:'Prefix Sum',tag:'Arrays',bg:'#EAF3DE',tc:'#3B6D11',desc:'Precompute cumulative sums to answer range queries in O(1).',signal:'"Sum of subarray", "range sum", "product except self"; often combined with HashMap to track prefix sums.',edgeCases:'Zero sum, negative numbers, sum equals K multiple times, empty range, single element.',ex:'Subarray Sum Equals K, Range Sum Query, Product Except Self'},
  {name:'Trie (Prefix Tree)',tag:'Strings',bg:'#EAF3DE',tc:'#3B6D11',desc:'Tree for storing strings character by character. O(L) search/insert.',signal:'"Word search", "auto-complete", "prefix", "dictionary words"; need to check many strings sharing prefixes.',edgeCases:'Empty word, single character, word is prefix of another, no matching word, all words same prefix.',ex:'Implement Trie, Word Search II, Auto-complete, Replace Words'},
  {name:'Greedy',tag:'Optimization',bg:'#FCEBEB',tc:'#A32D2D',desc:'Always pick the locally optimal choice. Prove greedy works via exchange argument.',signal:'"Can you reach", "jump", "assign", "schedule"; locally optimal choice leads to global optimum; must prove it.',edgeCases:'Impossible to reach goal, single step only, all same value, must jump exactly K steps.',ex:'Jump Game, Gas Station, Assign Cookies, Task Scheduler'},
] satisfies PatternCard[];

export const systemDesignTopics = [
  {week:'Week 5 (M2)',title:'Foundations',intro:'Before designing any system, you need a shared vocabulary with your interviewer. These concepts are the building blocks every system design answer references — understanding them lets you reason about trade-offs instead of memorizing diagrams.',items:[
    {concept:'Scalability: vertical vs horizontal',explanation:'Vertical means bigger machines (finite limits). Horizontal means more machines (requires load balancing, data partitioning). Interviewers want to hear you default to horizontal for web-scale systems.'},
    {concept:'CAP theorem + PACELC',explanation:'In a network partition, you pick consistency or availability (CAP). PACELC extends this: even without partitions, you trade latency for consistency. Know which your system needs.'},
    {concept:'Latency, throughput, availability',explanation:'Latency = response time (ms). Throughput = requests per second. Availability = uptime percentage. Design trade-offs between these three.'},
    {concept:'Load balancers (L4 vs L7)',explanation:'L4 works at transport level (TCP/UDP), cheap, fast. L7 works at app level (HTTP), smarter routing but higher latency. Choose based on whether you need app-aware routing.'},
  ]},
  {week:'Week 6 (M2)',title:'Data & Storage',intro:'How you store data defines everything downstream: query speed, consistency guarantees, and cost. SQL and NoSQL each excel in different scenarios; consistent hashing and sharding let you scale beyond a single machine.',items:[
    {concept:'SQL vs NoSQL trade-offs',explanation:'SQL offers ACID, schema, joins, but scales vertically. NoSQL offers horizontal scale, flexibility, but weaker consistency and no joins. Choose based on query patterns and consistency needs.'},
    {concept:'Sharding strategies',explanation:'Distribute data across machines by range (user ID 1-1M on shard 1, 1M-2M on shard 2) or hash (hash(key) % num_shards). Hash sharding is resilient to uneven data distribution.'},
    {concept:'Replication (leader-follower)',explanation:'Replicas keep copies of data for redundancy and read scaling. Leader takes writes, followers replicate. Adds latency for writes but multiplies read capacity.'},
    {concept:'Consistent hashing',explanation:'Distributes cache nodes and database shards across a ring. When a node dies, only a fraction of keys rehash to new locations, unlike mod-based hashing which rehashes everything.'},
  ]},
  {week:'Week 7 (M2)',title:'Caching & CDN',intro:'Caching is the simplest, most effective scaling tool you have. A small cache near your user or database can turn a 100ms query into 1ms. CDNs cache at the edge, closer to your global users.',items:[
    {concept:'Cache eviction (LRU, LFU)',explanation:'When cache is full, evict least-recently-used (LRU) or least-frequently-used (LFU) entries. LRU is simpler; LFU adapts better to changing access patterns.'},
    {concept:'Write-through vs write-back',explanation:'Write-through: write to cache and DB synchronously (slow but consistent). Write-back: write to cache, return, flush to DB later (fast but risk of loss if cache dies).'},
    {concept:'CDN & edge caching',explanation:'CDN caches static content (images, CSS) at servers near users globally. Reduces latency and origin load. Best for content with long TTL.'},
    {concept:'Redis patterns',explanation:'Redis is an in-memory cache/data store. Use it for sessions, rate limiting, leaderboards, real-time counters. Single-threaded but fast; use replication for HA.'},
  ]},
  {week:'Week 8 (M2)',title:'Case Study: URL Shortener + Twitter',intro:'Case studies tie theory to practice. You\'ll see how to apply scalability concepts to real problems: encoding short IDs, generating them uniquely across machines, and handling massive fan-out.',items:[
    {concept:'Base62 encoding, ID generation',explanation:'Shorten long URLs by encoding them to shorter strings (Base62 uses 62 characters: 0-9, a-z, A-Z). Generate globally unique IDs using Snowflake (timestamp + machine ID + sequence) or UUID.'},
    {concept:'Fan-out on write vs read',explanation:'Twitter: write fan-out pushes each tweet to followers\' timelines immediately (write cost, fast reads). Alternatively, pull fan-out reads from followers on demand (fast writes, read cost).'},
    {concept:'Timeline generation',explanation:'Aggregate posts from all followed accounts sorted by time. Precompute and cache timelines for active users; compute on-demand for inactive users.'},
    {concept:'Snowflake ID, UUID',explanation:'Snowflake: 64-bit ID with timestamp + machine ID + sequence, sortable, no coordination. UUID: 128-bit globally unique, no coordination, but not sortable.'},
  ]},
  {week:'Week 9 (M2)',title:'Messaging & Async',intro:'Real-world systems are asynchronous. Message queues decouple producers from consumers, handle spikes, and make systems resilient to failures. Pub-Sub patterns broadcast events to many listeners.',items:[
    {concept:'Message queues (Kafka, RabbitMQ)',explanation:'Kafka: distributed, persisted, high-throughput log-based queue (replayed). RabbitMQ: simpler, in-memory, good for task queues and work distribution. Choose Kafka for event streaming, RabbitMQ for RPC-like work.'},
    {concept:'Pub-Sub pattern',explanation:'Decouple producers from consumers. Producer publishes to a topic; many consumers subscribe and receive all messages. Good for notifications, event broadcasts.'},
    {concept:'Event-driven architecture',explanation:'Services communicate via events instead of direct RPC. Service A publishes "user_created" event; services B and C listen and react independently. Increases resilience and scalability.'},
    {concept:'Rate limiting (token bucket)',explanation:'Limit requests per user/IP to prevent abuse and protect capacity. Token bucket: accumulate tokens at fixed rate, consume one per request. Allows bursty traffic up to bucket size.'},
  ]},
  {week:'Week 10 (M3)',title:'Distributed Systems',intro:'At scale, your system spans machines and networks, introducing new failures: network partitions, machine crashes, clock skew. Understanding consensus and transactions is critical.',items:[
    {concept:'Design key-value store (DynamoDB)',explanation:'Distributed hash table with replication and sharding. Partition by key hash; replicate across 3 machines for durability. DynamoDB adds eventual consistency and tunable latency.'},
    {concept:'Consensus: Raft / Paxos overview',explanation:'Algorithms for distributed systems to agree on a value despite failures. Raft is simpler: leader election, log replication. Paxos is more complex but more proven. Both ensure safety.'},
    {concept:'Distributed cache (Memcached)',explanation:'Memcached is a distributed in-memory cache: no persistence, no replication, simple protocol. Consistent hashing distributes keys across cache servers. Fast for simple get/set.'},
    {concept:'2-phase commit',explanation:'Atomic transaction across multiple databases: phase 1 prepare (all nodes lock and vote), phase 2 commit (all proceed or all rollback). Slow and not partition-tolerant; use saga pattern instead.'},
  ]},
  {week:'Week 11 (M3)',title:'Real-time & Search',intro:'Push notifications and full-text search are features users expect. WebSockets enable real-time bidirectional communication; Elasticsearch indexes and searches text at scale.',items:[
    {concept:'Design notification system',explanation:'Publisher sends notification to queue; notification service consumes, batches, and sends to user via email/SMS/push. Use fan-out queue for scalability. Idempotency prevents duplicate sends.'},
    {concept:'WebSockets vs long-polling',explanation:'WebSockets: persistent bidirectional connection (real-time, low latency, resource-heavy). Long-polling: client polls server periodically (works behind proxies, higher latency, higher load).'},
    {concept:'Search: Elasticsearch basics',explanation:'Elasticsearch indexes documents and allows full-text search via inverted indices. Distributed, replicated, near real-time. Good for logs, user search, analytics.'},
    {concept:'Design type-ahead / autocomplete',explanation:'Prefix matching in real-time as user types. Use Trie or inverted index. Precompute popular searches; cache results. Suggestion ranking by frequency or context.'},
  ]},
  {week:'Week 12 (M3)',title:'Mega Round Review',intro:'Final week: consolidate all 12 case studies, practice end-to-end design under time pressure, and rehearse trade-off discussions. You\'ve seen patterns — now combine them fluently.',items:[
    {concept:'Design YouTube / Netflix',explanation:'Video platform: choose S3 or HDFS for video storage, CDN for distribution, Kafka for events, database for metadata, cache for popular videos. Transcoding pipeline for multiple qualities.'},
    {concept:'Design Uber / Lyft',explanation:'Real-time matching: geospatial indexing (quadtree, R-tree) to find drivers near a request. Messaging for notifications. Payment and trip history in ACID store. Redis for leaderboards.'},
    {concept:'Design WhatsApp / Slack',explanation:'Real-time chat: WebSockets for delivery, persistent queue for offline messages, eventual consistency for distributed replicas. Message deduplication via unique IDs.'},
    {concept:'Review all designs + trade-offs',explanation:'For each system, articulate: scalability (sharding, replication, caching), consistency model, failure modes, and monitoring. Always justify every component choice.'},
  ]},
] satisfies SystemDesignTopic[];
