/* This file is generated by scripts/generate-trace-registry.mjs. */
import definition0 from "@/content/visualizations/problems/0001-two-sum/definition";
import definition1 from "@/content/visualizations/problems/0003-longest-substring-without-repeating-characters/definition";
import definition2 from "@/content/visualizations/problems/0011-container-with-most-water/definition";
import definition3 from "@/content/visualizations/problems/0015-3sum/definition";
import definition4 from "@/content/visualizations/problems/0020-valid-parentheses/definition";
import definition5 from "@/content/visualizations/problems/0021-merge-two-sorted-lists/definition";
import definition6 from "@/content/visualizations/problems/0049-group-anagrams/definition";
import definition7 from "@/content/visualizations/problems/0098-validate-binary-search-tree/definition";
import definition8 from "@/content/visualizations/problems/0102-binary-tree-level-order-traversal/definition";
import definition9 from "@/content/visualizations/problems/0104-maximum-depth-of-binary-tree/definition";
import definition10 from "@/content/visualizations/problems/0125-valid-palindrome/definition";
import definition11 from "@/content/visualizations/problems/0128-longest-consecutive-sequence/definition";
import definition12 from "@/content/visualizations/problems/0141-linked-list-cycle/definition";
import definition13 from "@/content/visualizations/problems/0206-reverse-linked-list/definition";
import definition14 from "@/content/visualizations/problems/0208-implement-trie-prefix-tree/definition";
import definition15 from "@/content/visualizations/problems/0217-contains-duplicate/definition";
import definition16 from "@/content/visualizations/problems/0238-product-of-array-except-self/definition";
import { definition as definition17 } from "@/content/visualizations/problems/0242-valid-anagram/definition";
import definition18 from "@/content/visualizations/problems/0347-top-k-frequent-elements/definition";
import definition19 from "@/content/visualizations/problems/0704-binary-search/definition";

import type { TraceProblemDefinition } from "@/lib/visualizer/types";

export const traceDefinitions = [
  definition0,
  definition1,
  definition2,
  definition3,
  definition4,
  definition5,
  definition6,
  definition7,
  definition8,
  definition9,
  definition10,
  definition11,
  definition12,
  definition13,
  definition14,
  definition15,
  definition16,
  definition17,
  definition18,
  definition19,
] as const satisfies readonly TraceProblemDefinition[];
