/* This file is generated by scripts/generate-trace-registry.mjs. */
import type { TraceProblemRuntime } from "@/lib/visualizer/types";

export type TraceRuntimeModule = { runtime: TraceProblemRuntime };

export const traceRuntimeLoaders: Readonly<
  Record<string, () => Promise<TraceRuntimeModule>>
> = {
  "two-sum": () =>
    import("@/content/visualizations/problems/0001-two-sum/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "longest-substring-without-repeating-characters": () =>
    import("@/content/visualizations/problems/0003-longest-substring-without-repeating-characters/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "container-with-most-water": () =>
    import("@/content/visualizations/problems/0011-container-with-most-water/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "3sum": () =>
    import("@/content/visualizations/problems/0015-3sum/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "valid-parentheses": () =>
    import("@/content/visualizations/problems/0020-valid-parentheses/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "merge-two-sorted-lists": () =>
    import("@/content/visualizations/problems/0021-merge-two-sorted-lists/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "group-anagrams": () =>
    import("@/content/visualizations/problems/0049-group-anagrams/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "validate-binary-search-tree": () =>
    import("@/content/visualizations/problems/0098-validate-binary-search-tree/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "binary-tree-level-order-traversal": () =>
    import("@/content/visualizations/problems/0102-binary-tree-level-order-traversal/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "maximum-depth-of-binary-tree": () =>
    import("@/content/visualizations/problems/0104-maximum-depth-of-binary-tree/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "valid-palindrome": () =>
    import("@/content/visualizations/problems/0125-valid-palindrome/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "longest-consecutive-sequence": () =>
    import("@/content/visualizations/problems/0128-longest-consecutive-sequence/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "linked-list-cycle": () =>
    import("@/content/visualizations/problems/0141-linked-list-cycle/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "reverse-linked-list": () =>
    import("@/content/visualizations/problems/0206-reverse-linked-list/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "implement-trie-prefix-tree": () =>
    import("@/content/visualizations/problems/0208-implement-trie-prefix-tree/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "contains-duplicate": () =>
    import("@/content/visualizations/problems/0217-contains-duplicate/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "product-of-array-except-self": () =>
    import("@/content/visualizations/problems/0238-product-of-array-except-self/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "valid-anagram": () =>
    import("@/content/visualizations/problems/0242-valid-anagram/runtime").then(
      (module) => ({ runtime: module.runtime }),
    ),
  "top-k-frequent-elements": () =>
    import("@/content/visualizations/problems/0347-top-k-frequent-elements/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
  "binary-search": () =>
    import("@/content/visualizations/problems/0704-binary-search/runtime").then(
      (module) => ({ runtime: module.default }),
    ),
};
